version: "3"

services:
  redis:
    image: "redis:latest"
    container_name: redis-local
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network

  api:
    build: .
    container_name: app-api-md
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - redis-network
    depends_on:
      - redis
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8008 --reload

volumes:
  redis-data:

networks:
  redis-network:
    driver: bridge
